### ISSUE TITLE
I can't list contracts

### ISSUE THREAD

**Issue by roidelapluie** [kalmanolah/925r#35]
```
[02/Sep/2017 17:35:59] "GET /api/v1/my_contracts?page_size=9999 HTTP/1.1" 301 0                                                              [44/1363]
Internal Server Error: /api/v1/my_contracts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/generics.py", line 172, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/usr/local/lib/python3.5/site-packages/rest_framework/pagination.py", line 223, in paginate_queryset
    return list(self.page)
  File "/usr/local/lib/python3.5/_collections_abc.py", line 817, in __iter__
    v = self[i]
  File "/usr/local/lib/python3.5/site-packages/django/core/paginator.py", line 120, in __getitem__
    self.object_list = list(self.object_list)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.5/site-packages/polymorphic/query.py", line 445, in iterator
    real_results = self._get_real_instances(base_result_objects)
  File "/usr/local/lib/python3.5/site-packages/polymorphic/query.py", line 328, in _get_real_instances
    real_concrete_class = base_object.get_real_instance_class()
  File "/usr/local/lib/python3.5/site-packages/polymorphic/models.py", line 117, in get_real_instance_class
    and not issubclass(model, self.__class__._meta.proxy_for_model):
```

**Comment by roidelapluie** [comment]
That bug is on me.
